name: issue-workflow
on:
  issues:
    types: [opened]

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world issue
      - name: step2
        run: |
          echo hello world issue opened step 2
          echo github world issue opened step 2
