name: needs-workflow
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        run: echo "This is job1"
  this-job-needs-job1:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: this job needs job1
        run: echo "This job needs job1, so it will run after job1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: this job must be failed
        run: |
          echo "job must be failed"
          exit 1

  this-job-needs-job2:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
      - name: this job needs job2
        run: echo "This job needs job2, so it will run after job2"
