name: cache-workflow
on:
  push:
    paths:
      - "my-app/**"

jobs:
  cache-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Cache node.js modules
        uses: actions/cache@v3
        with: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('my-app/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          cd my-app
          npm install
      - name: Build
        run: |
          cd my-app
          npm run build
