name: pull-request-workflow from pr-branch another change 222
on: pull_request:
      types: [opened]

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world pull request
      - name: step2
        run: |
          echo hello world pull request step 2
          echo github world pull request step 2
